version: '3.3'
services:
  mongo:
    image: mongo:4.2.5
    hostname: mongo
    ports:
      - "27017:27017"
  main:
    build: ../Bullboard
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - '8080:8000'
